Add Navbar
phpbb/StyleGuideDesigner pull request #2
Opened 2017-06-16 10:54 UTC by sahil505

2017-06-16 13:50 UTC, hanakin commented on src/scss/components/_navbar.scss
> +		font-size: 17px;
pls use material design specs... all font-sizes should be based on material design and all units should be based on 8px grid

2017-06-16 13:50 UTC, hanakin commented on views/demo.pug
> +extends layout.pug
remove this file for now

2017-06-16 13:50 UTC, hanakin commented on views/documentation.pug
> +extends layout.pug
remove this file for now

2017-06-16 13:50 UTC, hanakin commented on views/index.pug
> +extends layout.pug
remove this file for now

2017-06-16 13:51 UTC, hanakin commented on views/layout.pug
> +							svg.c-navbar-menu-link-icon
this needs the icon object

2017-06-16 13:52 UTC, hanakin commented on views/layout.pug
> +				hr
remove this not necessary just add a border to the footer top

2017-06-16 13:52 UTC, hanakin commented on views/layout.pug
> +				a(href="https://github.com/sahil505/StyleGuideDesigner", target="_blank") Git
this needs a class

2017-06-16 13:52 UTC, hanakin commented on views/layout.pug
> +				p Developed for <a href="https://www.phpbb.com/" target="_blank">phpBB</a>
this needs a class

2017-06-16 13:52 UTC, hanakin commented on views/settings.pug
> +extends layout.pug
remove this file for now

2017-06-16 13:54 UTC, hanakin commented on views/layout.pug
> +							svg.c-navbar-menu-link-icon
again i am going to refer you to https://codepen.io/hanakin/pen/dRoZzO as a reference for how this should function for icons

2017-06-16 18:29 UTC, sahil505 commented on src/scss/components/_navbar.scss
> +		font-size: 17px;
done!

2017-06-16 18:30 UTC, sahil505 commented on views/layout.pug
> +							svg.c-navbar-menu-link-icon
done!

2017-06-16 18:30 UTC, sahil505 commented on views/layout.pug
> +				hr
done!

2017-06-16 18:30 UTC, sahil505 commented on views/layout.pug
> +				a(href="https://github.com/sahil505/StyleGuideDesigner", target="_blank") Git
done!

2017-06-16 18:30 UTC, sahil505 commented on views/layout.pug
> +				p Developed for <a href="https://www.phpbb.com/" target="_blank">phpBB</a>
done!

2017-06-16 22:47 UTC, hanakin commented on views/layout.pug
> +		block head
you can include the svg sprite file before this line right after body

2017-06-16 22:49 UTC, hanakin commented on views/layout.pug
> +				a.c-footer-icon(href="https://github.com/sahil505/StyleGuideDesigner", target="_blank") Git
if this is just an icon then use the same icon from above

2017-06-16 22:50 UTC, hanakin commented on views/layout.pug
> +							svg.o-icon
if we ever need to change the styling of the icon then you will need the component icon class as well for these...

2017-06-18 11:42 UTC, hanakin commented on src/scss/components/_navbar.scss
> +		color: #868686;
this should be a local variable in the future. infact all these should be variables that is why i said to just 100% use the component I already built verbatim. Until you get the hang of building your own

2017-06-18 11:42 UTC, hanakin commented on views/index.pug
> +extends layout.pug
remove this

2017-06-18 11:43 UTC, hanakin commented on views/layout.pug
> +		.svg-sprite(style="position: absolute; width: 0; height: 0;")
this is not nessecary to have a class here as you will never target it

2017-06-18 11:44 UTC, hanakin commented on views/layout.pug
> +			svg.editor-icons(xmlns="http://www.w3.org/2000/svg" style="position: absolute; width: 0; height: 0;")
the class name here should be app-icons rather than editor icons which is leftover from my markup of the forum components

2017-06-18 11:46 UTC, hanakin commented on views/layout.pug
> +		.svg-sprite(style="position: absolute; width: 0; height: 0;")
This needs to also be a partial file in the includes folder that you include in the layout via the include statment. You also did not need to use pug you could have left the html as it was.

2017-06-18 11:47 UTC, hanakin requested changes

2017-06-18 11:47 UTC, hanakin commented on src/scss/components/_navbar.scss
> +		color: #868686;
why did you not just use the component i provided for simplicity?

2017-06-18 11:49 UTC, hanakin commented on src/scss/components/_footer.scss
> +	border-top: groove;
remove this it looks really bad. also the text-align should really be applied to the individual elements and not the block for future reference but no big deal here

2017-06-18 13:38 UTC, sahil505 commented on views/layout.pug
> +		.svg-sprite(style="position: absolute; width: 0; height: 0;")
I thought you wanted it below the body tag. Okay, but where is the includes folder? Is there suppose to be one inside the views?

2017-06-18 13:38 UTC, sahil505 commented on views/layout.pug
> +			svg.editor-icons(xmlns="http://www.w3.org/2000/svg" style="position: absolute; width: 0; height: 0;")
Okay. app-icons it would be.

2017-06-18 22:50 UTC, hanakin requested changes

2017-06-18 22:50 UTC, hanakin commented on views/layout.pug
> +		div(style="position: absolute; width: 0; height: 0;")
this still needs to be extracted to its own file....

2017-06-18 23:37 UTC, hanakin approved these changes

2017-06-18 23:37 UTC, merged